// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdO2r_htPck9YiIJxArsiCkj0Uqx_9HOA',
    appId: '1:44716240931:web:8953cd517cbee91e19c196',
    messagingSenderId: '44716240931',
    projectId: 'appdev-1d487',
    authDomain: 'appdev-1d487.firebaseapp.com',
    storageBucket: 'appdev-1d487.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBLTCj16Fbdiscjzf2nm8E8antUSNKn7g',
    appId: '1:44716240931:android:d78c98c8cac1883b19c196',
    messagingSenderId: '44716240931',
    projectId: 'appdev-1d487',
    storageBucket: 'appdev-1d487.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGdOpug59VxT7CwNSOxIV26E8XiwMQKuY',
    appId: '1:44716240931:ios:9f70ab80c898a05819c196',
    messagingSenderId: '44716240931',
    projectId: 'appdev-1d487',
    storageBucket: 'appdev-1d487.appspot.com',
    iosBundleId: 'com.example.appdev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGdOpug59VxT7CwNSOxIV26E8XiwMQKuY',
    appId: '1:44716240931:ios:4a3ff2d021ed549319c196',
    messagingSenderId: '44716240931',
    projectId: 'appdev-1d487',
    storageBucket: 'appdev-1d487.appspot.com',
    iosBundleId: 'com.example.appdev.RunnerTests',
  );
}
